---
# tasks file for win_ad_install
- name: Install AD-Domain-Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present

#- name: Promote to domain controller
#  domain_controller:
#    domain_name: "ad1.${GUID}.example.opentlc.com"
#    safe_mode_password: jVMijRwLbI02gFCo2xkjlZ9lxEA7bm7zgg== 

- name: Ensure the named domain is reachable from the target host
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: result

- name: reboot AD server
  win_reboot:
    reboot_timeout: 3600 
  when: result.reboot_required

- name: check domain list
  win_command: nltest /dclist:"{{ ad_domain_name }}"

